application: weakish
version: 1
runtime: python
api_version: 1

default_expiration: "1d"

handlers:
- url: /
  static_files: weakish/index.xhtml
  upload: weakish/index.xhtml

- url: /zhtran
  script: stupidm_web_gae.py

- url: /pubkey.asc
  static_files: weakish/pubkey.asc
  upload: weakish/pubkey.asc
  mime_type: "text/plain"
  expiration: "3650d"
  secure: always

- url: /logo
  static_dir: logo
  expiration: "365d"

